---
title: "{{< var course.full-title >}}"
listing:
  id: most-recent-announcement
  contents: posts
  sort: "date desc"
  type: default
  max-items: 1
  fields: [title, subtitle, description, date, image, reading-time]
execute:
  freeze: false
---

**Instructors:** {{< var instructor.name >}} (Section {{< var instructor.section >}}) · {{< var instructor2.name >}} (Section {{< var instructor2.section >}})  \

::::: columns
::: {.column width="50%"}
**Contact**\
{{< var icon.mail >}} [{{< var instructor.email >}}](mailto:{{< var instructor.email >}}) ({{< var instructor.name >}})\
{{< var icon.mail >}} [{{< var instructor2.email >}}](mailto:{{< var instructor2.email >}}) ({{< var instructor2.name >}})\
{{< var icon.time >}} Office hours: <!-- TODO --> \
:::

::: {.column width="50%"}
**Lecture**\
{{< var course.time >}}\
{{< var building.name >}} ({{< var building.code >}}, {{< var building.ubc-wayfinding >}}, {{< var building.google-maps >}})\
:::
:::::

## Schedule
```{r}
#| label: setup
#| echo: false
#| message: false
light_theme <- quarto::theme_brand_gt("light-brand.yml")
dark_theme <- quarto::theme_brand_gt("dark-brand.yml")
```

::: {.panel-tabset}
### By unit

```{r}
#| label: unit-schedule
#| echo: false
#| message: false
#| renderings: [light, dark]
source(here::here("R", "render-unit-schedule.R"))
unit_schedule <- render_unit_schedule()

unit_schedule |> light_theme()
unit_schedule |> dark_theme()
```

### By week

```{r}
#| label: weekly-schedule
#| echo: false
#| message: false
#| renderings: [light, dark]
source(here::here("R", "render-weekly-schedule.R"))
weekly_schedule <- render_weekly_schedule()

weekly_schedule |> light_theme()
weekly_schedule |> dark_theme()
```
:::
